### ISSUE TITLE
Intermmitent freeze in tests while deleting environment

### ISSUE THREAD

**Issue by rimolive** [jboss-openshift/ce-arq#41]
The test was running as expected (see[1]), but maven didn't finish the test. After capturing Thread dump of surefire process, it seems that some threads started an infinite recursion (see [2]).

[1] https://gist.github.com/rimolive/56c0153cae0dc41120411a335cd6f2a8
[2] https://gist.github.com/rimolive/b888e2f8af87bb9b95fd87a2e7bfd587

**Comment by jwendell** [comment]
Could you post the logs here, or in a gist?
This pastebin is not available for everyone and it might expire.

**Comment by rimolive** [comment]
@jwendell, you are correct. I'll post in a different place

**Comment by rimolive** [comment]
I noticed that the test freezes after some errors in Remoting protocol. Details of the error in [1].

[1] https://gist.github.com/rimolive/85df12f2e4d2760a1ba99f10e3ec9dd6

**Comment by jwendell** [comment]
@rimolive any update on this? I was catch by this issue as well...

**Comment by rcernich** [comment]
It doesn't look like there's infinite recursion.  If there were, you'd get a stack overflow exception at some point.  Also, the top of the stack breaks you out of the "loop" and appears to be related to reading the error stream.  When I initially wrote the port forwarder, I had issues with the termination of the error streams and this may be the same problem.  I don't think this should have an effect any more, since we're invoking the port forwarder asynchronously.  The only side effect would be leaking connections.

**Comment by jwendell** [comment]
After a big investigation, found out the issue belongs to undertow.

Filled https://issues.jboss.org/browse/UNDERTOW-977 which was quickly fixed, because this is a known issue that had already being fixed on master, but not on 1.3.x branch, which is the one we use.

I've applied the patch locally and indeed it seems to work.

So, I'll ask UT maintainers for a 1.3.27.Final release so that we can benefit from it.
