### ISSUE TITLE
run oc import-image <stream> before test

### ISSUE THREAD

**Issue by l-d-j** [jboss-openshift/ce-arq#48]
We probably need to be able to  run oc import-image <stream> before test runs to make sure OpenShift sync image streams with current images in repository and is not trying to pull older images via sha256 of manifest.

**Comment by rcernich** [comment]
Looks like we can also update the image stream definition to include importPolicy.scheduled=true for the tags (under importPolicy).  I think we still need to manually import the tag before testing, but this will ensure folks are using the latest (or near latest) when testing on ocp.

**Comment by jwendell** [comment]
We could think of an annotation for each test class, for example, for eap64 tests:
```java
@ImportImageStream(name="jboss-eap64-openshift", allTags=true)
```
This could be implemented directly on arq-cube I think. (Need to verify if kubernetes-client has the ability to deal with imagestreams... but that's not a big deal I guess)

However...
- Given that ImageStreams reside on, by default, the "openshift" namespace, that would require special privileges...
- Also, the user might be pointing to a different template that points to a different ImageStream. So, hard coding the imagestream name in the annotation is not a good idea.

For @rcernich suggestion, it's way more simple to implement. I've opened CLOUD-1302 for tracking that.

**Comment by rcernich** [comment]
I don't see why we don't just run oc import-image before running the tests.  Also, I'm assuming the images are actually stored in our ci registry, which makes this moot anyway, since the release images (and what the jboss-image-streams.json definitions point to) are in registry.access.redhat.com.  Also, you can install image streams in your own namespace (e.g. the test project) and reference those by changing the IMAGE_STREAM_NAMESPACE parameter in the templates.   Also keep in mind that the templates reference an ImageStreamTag, which means the tag needs to exist for the named image stream.

**Comment by jwendell** [comment]
ok, got it. So it's more an internal thing to do - like adding that command to our CI script.

Closing as this is not a ce-arq issue.
